### ISSUE TITLE
maybe adding crop dusting?

### ISSUE THREAD

**Issue by NarigudoBR** [MaxNeedsSnacks/Skys-The-Limit#13]
because keyboards are not that cheap and its not nice, smashing the shift key to grow that sapling

**Comment by MaxNeedsSnacks** [comment]
You can instantly grow trees using Plant Matter in case you didn't know.
There's also bonsai pots for when you have managed to get a good supply of clay going that just sort of... passively grow the tree you plant in them.

I don't think I'll be adding another way of fertilising crops because of this, but I might increase the bonus that holding shift around a tree gives.
